apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer-api-lb
  namespace: wazuh
  labels:
    app.kubernetes.io/instance: wazuh
    app.kubernetes.io/name: wazuh-helm
spec:
  type: LoadBalancer
  ports:
    - name: indexer-rest
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: wazuh-wazuh-helm-indexer
    app.kubernetes.io/instance: wazuh
